name: bitshore
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_pickers:
  flutter_svg:
  google_fonts:
  font_awesome_flutter:
  flutter_circular_chart:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/DMSans-Bold.ttf
        - asset: fonts/DMSans-BoldItalic.ttf
        - asset: fonts/DMSans-Italic.ttf
        - asset: fonts/DMSans-Medium.ttf
        - asset: fonts/DMSans-MediumItalic.ttf
        - asset: fonts/DMSans-Regular.ttf

  uses-material-design: true
  assets:
    - assets/images/

